AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SingleLineMethods:
  Exclude:
    - spec/**/*

Style/LambdaCall:
  EnforcedStyle: braces

Layout/LineLength:
  Max: 120

RSpec/BeNil:
  EnforcedStyle: be

RSpec/ExampleLength:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

require:
  - rubocop-rspec
  - rubocop-rake
